version: "3.7"

services:
  item-db:
    container_name: item-db
    image: mongo:3
    volumes:
      - app-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  item-app:
    container_name: item-app
    image: item-app
    depends_on:
      - item-db
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-db:
